### ISSUE TITLE
Per Trade fee is not calculating 

### ISSUE THREAD

**Issue by nandhini-ramanujam** [helios-technologies/peatio-tech#62]
Hi, I have setup the Markets.yml with 0.1 as trading fee. But the same is not getting reduced in user account balance. Do we need any other configurations beyond this?

**Comment by ashanaakh** [comment]
Hi @nandhini-ramanujam, 

Please use [rubykube/peatio](https://github.com/rubykube/peatio) for this questions. 

Thanks!
